server:
  port: 8000
app:
  base_url: http://localhost:8000
  limit_size: 20
spring:
  spring:
    main:
      lazy-initialization: true
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: duyha2k4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql=true: true
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB
  application:
    name: jwt-cookie-auth
  session:
    cookie:
      http-only: true
      secure: false
      same-site: lax
debug: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO
jwt:
  signerKey: ${signerKey}
cloudinary:
  cloud_name: ${cloud_name}
  api_key: ${api_key}
  api_secret: ${api_secret}
